POST http://localhost:7038/Login
Content-Type: application/json

{
  "ID":"zxzx",
  "Password":"113"
}

###
POST http://localhost:7038/Join
Content-Type: application/json

{
  "ID":"zxzx",
  "Password":"113"
}