###
POST http://localhost:7038/Join
Content-Type: application/json

{
  "ID":"com2us",
  "Password":"fighting"
}

###
POST http://localhost:7038/Login
Content-Type: application/json

{
  "ID":"com2us",
  "Password":"fighting"
}

###
POST http://localhost:7038/DataLoad
Content-Type: application/json

{
  "ID":"com2us",
  "AuthToken":"mhryngts370pjthnxh7sbnkhw"
}

###
POST http://localhost:7038/Attend
Content-Type: application/json

{
  "ID":"com2us",
  "AuthToken":"mhryngts370pjthnxh7sbnkhw"
}

###
POST http://localhost:7038/AttendGift
Content-Type: application/json

{
  "ID":"com2us",
  "AuthToken":"mhryngts370pjthnxh7sbnkhw"
}

###
POST  http://localhost:7038/Mail
Content-Type: application/json

{
  "ID": "com2us",
  "AuthToken": "mhryngts370pjthnxh7sbnkhw"
}