###
POST http://localhost:7038/Join
Content-Type: application/json

{
  "ID":"test",
  "Password":"man"
}

###
POST http://localhost:7038/Login
Content-Type: application/json

{
  "ID":"test",
  "Password":"man"
}

###
POST http://localhost:7038/PlayerCreate
Content-Type: application/json

{
  "ID":"test",
  "AuthToken": "ba26n65egjemh06n7zhc6ftr9"
}

###
POST http://localhost:7038/DataLoad
Content-Type: application/json

{
  "ID": "test",
  "PlayerID": "14",
  "AuthToken":"ba26n65egjemh06n7zhc6ftr9"
}

###
POST http://localhost:7038/Attend
Content-Type: application/json

{
  "ID":"test",
  "PlayerID":"14",
  "AuthToken":"ba26n65egjemh06n7zhc6ftr9"
}

###
POST  http://localhost:7038/Mail
Content-Type: application/json

{
  "ID":"test",
  "PlayerID": "14",
  "AuthToken": "ba26n65egjemh06n7zhc6ftr9"
}

###
POST  http://localhost:7038/ReceiveMail
Content-Type: application/json

{
  "ID":"test",
  "PlayerID": "14",
  "AuthToken": "ba26n65egjemh06n7zhc6ftr9"
}

###
POST  http://localhost:7038/Inventory
Content-Type: application/json

{
  "ID":"test",
  "PlayerID": "14",
  "AuthToken": "ba26n65egjemh06n7zhc6ftr9"
}